# Generated by Django 4.0 on 2022-07-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='specialty',
            new_name='skill',
        ),
    ]
