# Generated by Django 4.0 on 2022-07-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='speciality',
            new_name='skill',
        ),
    ]
