# Generated by Django 4.0 on 2022-07-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_rename_speciality_worker_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='skill',
            new_name='specialty',
        ),
    ]
