# Generated by Django 4.0 on 2022-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ManyToManyField(to='workers.Worker'),
        ),
    ]
