# Generated by Django 4.0 on 2022-07-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerlocationjobinterval',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
    ]
