# Generated by Django 4.0 on 2022-07-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_workerlocationjobinterval_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('location',)},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='location',
        ),
    ]
